[
  " Head east on SH 11 ",
  " At the roundabout, take the 3rd exit and stay on SH 11 ",
  " Turn left at Gold Loan Sonipat onto Delhi Rd/SH 11 ",
  " Turn right at Bahalgarh Flyover ATM onto NH 44 ",
  " Use the 2nd from the left lane to keep left ",
  " Continue straight ",
  " Use the left lane to turn slightly left onto NH 44 ",
  " Turn left ",
  " Turn right ",
  " Turn left onto Niftem Rd ",
  " At the roundabout, take the 3rd exit ",
  " Turn right onto Janti Kalan Rd ",
  " Turn left ",
  " Turn right ",
  " Turn left onto NH 44 ",
  " Continue straight to stay on NH 44 ",
  " Turn left to merge with NH9 ",
  " Keep right to continue on Outer Ring Rd/Peera Garhi Flyover ",
  " Keep right to continue on Bhera Enclave Underpass/Outer Ring Rd ",
  " Slight right onto Vikaspuri Flyover ",
  " Slight right onto Outer Ring Rd ",
  " Turn left onto Najafgarh Rd/Shivaji Marg ",
  " Make a U-turn ",
  " Turn left after Metro Pillar Number 575 (on the left) "
]